set -g default-term "tmux-256color"

set -g bell-action any
set -g visual-bell off

set -g default-shell "/usr/bin/zsh"

set-option -sg escape-time 10

set -g prefix C-a
unbind C-b
bind C-a send-prefix

unbind C-Left
unbind C-Right
unbind C-Up
unbind C-Down

set -g mouse on
set -g terminal-overrides 'xterm*:smcup@:rmcup@:Tc'

bind q killp

bind F set -w window-size

bind m set monitor-activity
bind y set synchronize-panes\; display 'synchronize-panes #{?synchronize-panes,on,off}'

# Enable copy/paste
setw -g mode-keys vi
unbind -T copy-mode-vi Enter
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -i -f -selection primary | xclip -i -selection clipboard"

source ~/.tmux.theme.conf

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'

run -b '~/.tmux/plugins/tpm/tpm'
